#ifndef RAIZ_PARSER_OPERATORS_H
#define RAIZ_PARSER_OPERATORS_H

typedef enum {
  RAIZ_OPERATOR_SUM,
  RAIZ_OPERATOR_SUBTRACT,
  RAIZ_OPERATOR_MULTIPLY,
  RAIZ_OPERATOR_DIVIDE,
  RAIZ_OPERATOR_EQUAL,
  RAIZ_OPERATOR_NOT_EQUAL,
  RAIZ_OPERATOR_ALMOST_EQUAL,
  RAIZ_OPERATOR_GREATER,
  RAIZ_OPERATOR_LESSER,
  RAIZ_OPERATOR_GREAT_OR_EQUAL,
  RAIZ_OPERATOR_LESS_OR_EQUAL,
  RAIZ_OPERATOR_TYPE_CAST,
} Operator;

#endif // RAIZ_PARSER_OPERATORS_H
